apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:25.0.1
  db:
    vendor: postgres
    host: keycloak-cluster-rw.keycloak.svc.cluster.local
    usernameSecret:
      name: keycloak-postgres-user-secret
      key: username
    passwordSecret:
      name: keycloak-postgres-user-secret
      key: password
  http:
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: authdev.tailorw.net
  proxy:
    headers: xforwarded
  ingress:
    className: nginx

