apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:25.0.1
  startOptimized: false
  db:
    vendor: postgres
    database: keycloak
    host: keycloak-cluster-rw.keycloak.svc.cluster.local
    port: 5432
    usernameSecret:
      name: keycloak-postgres-user-secret
      key: username
    passwordSecret:
      name: keycloak-postgres-user-secret
      key: password
  http:
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: authdev.tailorw.net
  proxy:
    headers: xforwarded
  ingress:
    className: nginx
  additionalOptions:
    - name: db
      value: postgres
    - name: db-driver
      value: org.postgresql.Driver
    - name: db-url
      value: "jdbc:postgresql://keycloak-cluster-rw.keycloak.svc.cluster.local:5432/keycloak"


